# Introduction

Tensorflow is an end to end open source machine learning platform for everyone. It gives developers the flexibility of dataflow and differentiable programming.

More importantly, its a symbolic math library and its used for machine learning applications such as neural networks, deep learning. It can be used for research and production. It runs on multiple CPUs and GPUs.

Tensorflow was developed by the google brain team, the first version was released on the 11th of Febuary, 2017. Its an open source library written in python, c++ and CUDA. It is a cross-platform application that is, it is available on Linux, macOS, Windows, android, JavaScript. 


For more about tensorflow, do check out their website on https://www.tensorflow.org

As the name implies its a framework that is defined to run on computations involving tensors.

Tensors can be basically described as a generalization of vectors and matrices to potentially higher dimensions. Tensorflow represents tensors as an n-dimensional array of based datatypes.

All tensorflow programs involves basic manipulations of tensors (tf.Tensors).
A tf.Tensor object represents a partially defined computation that will always produce or operate on discrete/ continuous values.

Just has we have in numpy, tf.Tensor has the following support of all datatypes in numpy. 

Type of tensors include: tf.Variable (tensor variable), tf.constant(tensor constants), tf.placeholder (tensor placeholders).

Note: Tensorflow values are immutable (which implies that a single execution of tensors only have a single value).


In [1]:
import tensorflow as tf
tf.__version__

'2.0.0'

In [2]:
import numpy as np
import sklearn as sk
import seaborn as sns
import tensorflow.compat.v1 as tf
tf.disable_eager_execution()
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
import os

### creating your first graph

In [5]:
x = tf.Variable(34, name = 'x')
y = tf.Variable(12, name = 'y')
z = tf.Variable(45, name = 'z')
f = pow(x,3)+pow(x,2)*y +y*z

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    init.run()
    result = f.eval()

In [6]:
result

53716

In [15]:
a1 = tf.constant(3)
a2 = a1 +12
a3 = a2 -8

with tf.Session() as sess:
    #init = tf.global_variables_initializer()
    init.run()
    a = a3.eval()

In [16]:
a

7

In [21]:
m = tf.ones((20,5))
n = tf.zeros((5,20))
k = tf.ones((5,5))

y = tf.matmul(n,m) + k

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    init.run()
    matrix = y.eval()
    
print(matrix)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [27]:
type(matrix)

numpy.ndarray

In [29]:
# matrix determinant
arr = np.array([[2.0,4.0,6.6],
                [6.6,8.2,1.1],
                [7.4,4.1,2.9]])
v= tf.matrix_determinant(arr)
with tf.Session() as sess:
    out = v.eval()
    print(out)

-227.352


In [77]:
# inverse of a matrix
inv_mat = tf.matrix_inverse(arr)
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    init.run()
    inv = inv_mat.eval()
    print(inv)

[[-0.08475844 -0.06800028  0.21869172]
 [ 0.04838312  0.18930997 -0.18192055]
 [ 0.14787642 -0.09412717  0.04398466]]


In [78]:
# diagonal matrix
diag = tf.matrix_diag(inv_mat)
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    init.run()
    diagonal = diag.eval()
    print(diagonal)

[[[-0.08475844  0.          0.        ]
  [ 0.         -0.06800028  0.        ]
  [ 0.          0.          0.21869172]]

 [[ 0.04838312  0.          0.        ]
  [ 0.          0.18930997  0.        ]
  [ 0.          0.         -0.18192055]]

 [[ 0.14787642  0.          0.        ]
  [ 0.         -0.09412717  0.        ]
  [ 0.          0.          0.04398466]]]


In [79]:
# transpose
trans = tf.matrix_transpose(inv_mat)
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    init.run()
    trans_n = trans.eval()
    print(trans_n)

[[-0.08475844  0.04838312  0.14787642]
 [-0.06800028  0.18930997 -0.09412717]
 [ 0.21869172 -0.18192055  0.04398466]]


In [35]:
# max args
dis = tf.argmax([3,4,20,15], name = 'dis')
with tf.Session() as sess:
    print(dis.eval())

2


In [37]:
# min args
dis = tf.argmin([4,3,20,15], name = 'dis')
with tf.Session() as sess:
    print(dis.eval())

1


In [41]:
# addition
a = tf.Variable(3)
b = tf.Variable(5)
c = tf.add(a,b)

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    init.run()
    print(c.eval())

8


In [43]:
# argmax according to axis

arg = tf.argmax(arr, axis = 1)
with tf.Session() as sess:
    nit = tf.global_variables_initializer()
    init.run()
    print(arg.eval())

[2 1 0]


In [46]:
arr

array([[2. , 4. , 6.6],
       [6.6, 8.2, 1.1],
       [7.4, 4.1, 2.9]])

In [47]:
# argmax according to axis

arg = tf.argmin(arr, axis = 0)
with tf.Session() as sess:
    nit = tf.global_variables_initializer()
    init.run()
    print(arg.eval())

[0 0 1]


In [51]:
# Arg sorting
b = tf.argsort(arr,axis=1,direction='ASCENDING',name='b')
c = tf.keras.backend.eval(b)
print(c)

[[0 1 2]
 [2 0 1]
 [2 1 0]]


In [8]:
# confusion matrix
a = tf.random_uniform((90,),minval = 0, maxval = 1)
b = tf.random_uniform((90,), minval = 0, maxval =1)
pred = tf.round(a, 'pred')
y_true = tf.round(b,'y_true')
confusion_mat = tf.confusion_matrix(pred, y_true, name = 'confusion_Matrix')
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    init.run()
    print(confusion_mat.eval())

[[15 18]
 [27 30]]


In [68]:
# cast - casting a tensor to a new type
x = tf.constant([1.8,2.2, 3.5,4.9], dtype = tf.float32)
rea = tf.dtypes.cast(x, tf.int32)
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    init.run()
    print(rea.eval())

[1 2 3 4]


In [73]:
# cummulative sum
cum_sum = tf.cumsum(x, axis = 0, name = 'cum_sum')
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    init.run()
    print(cum_sum.eval())

[ 1.8  4.   7.5 12.4]


# Place holders

In [80]:
# placeholders are like inputs to dummy containers
# they hold informations to be processed.

A = tf.placeholder(tf.float32, shape = (None,3))
B = A + 5

with tf.Session() as sess:
    b_val = B.eval(feed_dict = {A:[[1,2,3]]})
    b_val_u = B.eval(feed_dict = {A:[[4,5,6],[7,8,9]]})
print(b_val)

[[6. 7. 8.]]


In [81]:
print(b_val_u)

[[ 9. 10. 11.]
 [12. 13. 14.]]
